<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0-windows</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.15.8" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SevenZipExtractor\SevenZipExtractor.csproj" />
  </ItemGroup>

</Project>
